In [6]:
# Loading the dataset using pandas

import pandas as pd
csv_file_path_dir = r'C:/Users/tinat/OneDrive/Desktop/Customer behaviour Analysis/Dataset_Raw/archive/'
csv_file_name='shopping_data.csv'
csv_file_path=csv_file_path_dir + csv_file_name
df = pd.read_csv(csv_file_path)
df.head()

,Unnamed: 0,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Color,Order Date,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,0,1,55,Male,Blouse,Clothing,53,Kentucky,Gray,1/1/2023,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,1,2,19,Male,Sweater,Clothing,64,Maine,Maroon,1/1/2023,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,2,3,50,Male,Jeans,Clothing,73,Massachusetts,Maroon,1/1/2023,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,3,4,21,Male,Sandals,Footwear,90,Rhode Island,Maroon,1/1/2023,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,4,5,45,Male,Blouse,Clothing,49,Oregon,Turquoise,1/1/2023,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              3900 non-null   int64
 1   Customer ID             3900 non-null   int64
 2   Age                     3900 non-null   int64
 3   Gender                  3900 non-null   object
 4   Item Purchased          3900 non-null   object
 5   Category                3900 non-null   object
 6   Purchase Amount (USD)   3900 non-null   int64
 7   Location                3900 non-null   object
 8   Color                   3900 non-null   object
 9   Order Date              3900 non-null   object
 10  Review Rating           3874 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(5), object(12)
memory usage: 548.6+ KB

In [8]:
# Summary statistics using .describe()
df.describe(include='all')

,Unnamed: 0,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Color,Order Date,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3874.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,NaN,2,25,4,NaN,50,25,365,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,Olive,7/14/2023,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,NaN,2652,171,1737,NaN,96,177,22,NaN,2847,675,2223,2223,NaN,677,584
mean,1949.500000,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,3.751394,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,0.716386,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,0.000000,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,974.750000,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1949.500000,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2924.250000,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3899.000000,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [9]:
#deleting un named coloumn
del df["Unnamed: 0"]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Color                   3900 non-null   object
 8   Order Date              3900 non-null   object
 9   Review Rating           3874 non-null   float64
 10  Subscription Status     3900 non-null   object
 11  Shipping Type           3900 non-null   object
 12  Discount Applied        3900 non-null   object
 13  Promo Code Used         3900 non-null   object
 14  Previous Purchases      3900 non-null   int64
 15  Payment Method          3900 non-null   object
 16  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(12)
memory usage: 518.1+ KB

In [11]:
# Checking if missing data or null values are present in the dataset

df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Color                      0
Order Date                 0
Review Rating             26
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [12]:
# Inputing missing values in Review Rating column with the median rating of the product category

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [13]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Color                     0
Order Date                0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [14]:
# Renaming columns according to snake casing for better readability and documentation

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'color', 'order_date', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'promo_code_used', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [16]:
# create a new column age_group
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [17]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [18]:
# Standardize purchase frequency labels:
# Replace "Fortnightly" with "Bi-Weekly"
# Replace "Every 3 Months" with "Quarterly"
df["frequency_of_purchases"] = df["frequency_of_purchases"].replace({
    "Fortnightly": "Bi-Weekly",
    "Every 3 Months": "Quarterly"
})

In [19]:
df["frequency_of_purchases"].unique()

array(['Bi-Weekly', 'Weekly', 'Annually', 'Quarterly', 'Monthly'],
      dtype=object)

In [20]:
# Create purchase tiers based on amount ranges
df["purchase_tier"] = pd.cut(
    df["purchase_amount"],
    bins=[0, 33, 66, 100],
    labels=["Low", "Medium", "High"]
)

In [21]:
print(df["purchase_tier"].value_counts())

purchase_tier
High      1635
Medium    1546
Low        719
Name: count, dtype: int64

In [22]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [23]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [24]:
# Dropping promo code used column

df = df.drop('promo_code_used', axis=1)

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'color', 'order_date', 'review_rating',
       'subscription_status', 'shipping_type', 'discount_applied',
       'previous_purchases', 'payment_method', 'frequency_of_purchases',
       'age_group', 'purchase_tier'],
      dtype='object')

In [ ]:
# Connecting to MS SQL Server
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\tinat\anaconda3\envs\myenv\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\tinat\anaconda3\envs\myenv\lib\site-packages (2.0.45)
Requirement already satisfied: greenlet>=1 in c:\users\tinat\anaconda3\envs\myenv\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\tinat\anaconda3\envs\myenv\lib\site-packages (from sqlalchemy) (4.15.0)

In [27]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client 11.0', 'ODBC Driver 11 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [ ]:
# Install required libraries


from sqlalchemy import create_engine
from urllib.parse import quote_plus

server = "xxxxxxxxxxxxxx"   
database = "ShoppingData"

driver = quote_plus("ODBC Driver 18 for SQL Server")

engine = create_engine(
    f"mssql+pyodbc://@{server}/{database}?driver={driver}&trusted_connection=yes&TrustServerCertificate=yes"
)

# Test connection
with engine.connect() as conn:
    print("Connected successfully!")

Connected successfully!

In [29]:


# --------------------------
# Write DataFrame to SQL Server
# --------------------------
# if_exists='replace' will overwrite the table
# index=False prevents adding DataFrame index as a column
df.to_sql("shopping_data", engine, if_exists="replace", index=False)

print("✅ Data written successfully to SQL Server!")

✅ Data written successfully to SQL Server!